### ISSUE TITLE
Overlapped pins

### ISSUE THREAD

**Issue by nunobuica** [Mystist/bootstrap-waterfall#6]
Hi,

Thanks for this great plugin. I'm loading pins with images (different heights) on scroll, but sometimes i a few pins overlapped. I'm calling the addPins after loading images. If i trigger a window resize each time add pins, everything gets fine.

`$('#catalogs-list').imagesLoaded( function() {
  $('#catalogs-list').data('mystist.waterfall').addPins($(array));
//$(window).trigger('resize');
});`

![capturar](https://cloud.githubusercontent.com/assets/4409269/25739490/087e8a14-317a-11e7-91ad-8bc0530c866c.JPG)

Thanks!

**Comment by Mystist** [comment]
1. Typically, we don't need to use `addPins ` to add pins. Just pass in the markups(raw html) and everything else will works fine. (No need to wait for the images to be loaded.) Try it this proper way first.

**Comment by Mystist** [comment]
Typically, we don't need to use `addPins ` to init pins (use it when there are initial pins on the page). Just pass in the markups(raw html) and everything else will works fine. (No need to wait for the images to be loaded.) Try it this proper way first.

eg:
```html
<ul class="pin list-group">
  <li class="list-group-item">
    <a href="javascript:;">
      <img src="images/1.jpg" />
    </a>
  </li>
</ul>
<ul class="pin list-group">
  <li class="list-group-item">
    <a href="javascript:;">
      <img src="images/2.jpg" />
    </a>
  </li>
</ul>
<ul class="pin list-group">
  <li class="list-group-item">
    <a href="javascript:;">
      <img src="images/3.jpg" />
    </a>
  </li>
</ul>
```

```javascript
      $('.waterfall').waterfall();
```

**Comment by nunobuica** [comment]
Hi,

I need to use the addPins functions because i have a dynamic list with
infinite scroll. Initializing with the waterfall function works great, but
when i add some pins, sometimes they are overlapped.

Thanks,
Nuno

**Comment by liber-gong** [comment]
@nunobuica https://github.com/Mystist/bootstrap-waterfall/commit/afee1a08d6e9a276d235cc41a06ef16962f048e0

Pls fetch the latest code, thanks for your contribution!

**Comment by liber-gong** [comment]
BTW, typically, we don't need to use `addPins ` to init pins (use it when there are initial pins on the page). Just pass in the markups(raw html) and everything else will works fine. (No need to wait for the images to be loaded.)

eg:
```html
<ul class="pin list-group">
  <li class="list-group-item">
    <a href="javascript:;">
      <img src="images/1.jpg" />
    </a>
  </li>
</ul>
<ul class="pin list-group">
  <li class="list-group-item">
    <a href="javascript:;">
      <img src="images/2.jpg" />
    </a>
  </li>
</ul>
<ul class="pin list-group">
  <li class="list-group-item">
    <a href="javascript:;">
      <img src="images/3.jpg" />
    </a>
  </li>
</ul>
```

```javascript
// Make sure you run this after those markups available on the page
$('.waterfall').waterfall();
```

**Comment by nunobuica** [comment]
Great,

Its working!

Notes:
I'm not sure, but i think the resize is a litle bit slower
When the addPins function is called it won't load the pins without images
(404 not found) but they are displayed after a window resize.

Thanks,
Nuno

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
