### ISSUE TITLE
With Ajax technology

### ISSUE THREAD

**Issue by 2daye** [Mystist/bootstrap-waterfall#8]
How do you use ajax technology to call database resources?

**Comment by liber-gong** [comment]
@2daye It receives just markups, no matter it's comes from a ajax call or whatever.

Typically, our ajax call will returns a json list of items, within your success callback, you can generate the items data into markups, then pass it into bootstrap-waterfall.

If it's the first time you init it, run
```
$('.waterfall').data('bootstrap-waterfall-template', markups)
$('.waterfall').waterfall()
```

If it's to add some new pins after a ajax call, run
```
$('.waterfall').data('mystist.waterfall').addPins(markups)
```

The `markups` may looks like:
```
<ul class="pin list-group">
  <li class="list-group-item">
    <a href="javascript:;">
      <img src="images/1.jpg" />
    </a>
  </li>
</ul>
<ul class="pin list-group">
  <li class="list-group-item">
    <a href="javascript:;">
      <img src="images/2.jpg" />
    </a>
  </li>
</ul>
<ul class="pin list-group">
  <li class="list-group-item">
    <a href="javascript:;">
      <img src="images/3.jpg" />
    </a>
  </li>
</ul>
```

For more information, check it out here:
http://mystist.github.io/bootstrap-waterfall/getting-started/

**Comment by 2daye** [comment]
我会了，谢谢！
