### ISSUE TITLE
how do i make it with ajax for more pages?

### ISSUE THREAD

**Issue by GitCod-Man** [Mystist/bootstrap-waterfall#9]
how do i make it with ajax for more pages?
i want to use it with ajax for dynamic data,and which method can show it ?

**Comment by liber-gong** [comment]
@GitCod-Man 

Run `$('.waterfall').data('mystist.waterfall').addPins($elements)` whenever you want to add new pins!
Newly added pins will shows up when you scrolled to the bottom of page.

Try this code inside your ajax success callback, `$elements` should be the new pins markups.

You may also refer to https://github.com/Mystist/bootstrap-waterfall/issues/8

**Comment by GitCod-Man** [comment]
@Mystist Thanks! i have been already try this yesterday ,but my data is like page1 request ajax,and page2.page3..... request ajax , where can i know the page scrolled to the bottom and then i can request my server again!
 $.ajax({
        	  url:'/api/queryPug', data:{'currentPage':1},
        	  type:'post',
        	  success:function(result){
                 $('.waterfall').data('mystist.waterfall').addPins($(htmlpins));
} 
  this way can only run one time! but i want it go with page and page!

**Comment by GitCod-Man** [comment]
@Mystist which api can judge the page has been  scrolled to the bottom?  thanks!

**Comment by liber-gong** [comment]
@GitCod-Man Thanks for you use case, I will do a quick fix later today.

**Comment by GitCod-Man** [comment]
@Mystist Thanks! did you finished this work ?

**Comment by liber-gong** [comment]
@GitCod-Man Check it out here: https://github.com/Mystist/bootstrap-waterfall/commit/b5538bbf3bb7c2f1800d5d48df68ad91fb0c602f

Or just download the v0.2.7 version: https://github.com/Mystist/bootstrap-waterfall/releases

Sorry for the delay, thanks a lot!

**Comment by liber-gong** [comment]
Documentation updated:
http://mystist.github.io/bootstrap-waterfall/getting-started/

**Comment by GitCod-Man** [comment]
@Mystist Thanks!but id  didn't work .    <script>
       $('.waterfall')
          .data('bootstrap-waterfall-template', $('#waterfall-template').html())
       /*  .waterfall()  */
        .on('finishing.mystist.waterfall', function () {
        	console.log('bottom....');
        })
        .waterfall();
     </script>
when scroll to the bottom,it didn't print any message!

**Comment by liber-gong** [comment]
@GitCod-Man Have tried to run it locally? When you can successful run `gulp serve`, you will see an example at bottom of the `index.html`

**Comment by liber-gong** [comment]
@GitCod-Man First there need to be some initial pins and the `finishing` event will be fired when scroll to the bottom with no more pins to be loaded. (If there are more pins or zero pin to be loaded, the `finishing` event won't be fired)

Make sense?

**Comment by GitCod-Man** [comment]
@Mystist  yes, i had init my pins like the demo,and it shows rightly!but the finishing event didn't work when  scroll to the bottom .
        $('.waterfall')
          .data('bootstrap-waterfall-template', $('#waterfall-template').html())
         .waterfall() ;
       $('.waterfall').on('finishing.mystist.waterfall', function () {
        	console.log('bottom....');
        });
        //.waterfall();

**Comment by liber-gong** [comment]
@GitCod-Man Can you run it locally?

http://mystist.github.io/bootstrap-waterfall/getting-started/

```
Documentation
Setup
Install Nodejs on your computer. (Please use node 4)
Install yo and other required tools: npm install -g yo bower grunt-cli gulp
Clone the latest source code.
Run npm install, bower install to install devDependencies.
Run gulp. Make sure you can see Finished 'build' after xxx ms. Congratulations!
Examples
Run gulp serve to see the demo.

**Comment by liber-gong** [comment]
@GitCod-Man the `finishing` event won't fired if there are more pins to be loaded, try to scroll to the bottom again and again to load all the pins, and then the event will be fired.

**Comment by liber-gong** [comment]
@GitCod-Man Also please help make sure you've already uses the v0.2.7 version

**Comment by GitCod-Man** [comment]
@Mystist v0.2.7? but your lasted releases version is v0.2.4  
https://github.com/Mystist/bootstrap-waterfall/releases
<script src="/static/waterfall/js/bootstrap-waterfallv0.2.4.js"></script>

**Comment by liber-gong** [comment]
@GitCod-Man Sorry, Can you tell me where you get the v0.2.4 version? To get the latest version, you just need to click the download link from this page: http://mystist.github.io/bootstrap-waterfall/getting-started/

**Comment by GitCod-Man** [comment]
@Mystist Thanks ! you  make  great work!

**Comment by liber-gong** [comment]
@GitCod-Man Ok I see, it maybe from https://github.com/Mystist/bootstrap-waterfall/releases, where I haven't tag the version to be released, sorry for that~ (You will see the link `show 2 newer tags`, if you click to open it, you will see the latest version)

**Comment by ZhuRuiHeng** [comment]
请问你怎么解决下拉分页添加数据的

**Comment by ZhuRuiHeng** [comment]
> @Mystist谢谢！你做得很好！

请问你是怎么实现分页的

**Comment by liber-gong** [comment]
@ZhuRuiHeng 当页面滑动底部的时候，会触发一个“finishing”的callback，在那个callback里面可以请求ajax获取数据，然后把数据添加进去。

具体的代码：
``` javascript
// 初始化
$('.waterfall')
.data('bootstrap-waterfall-template', $('#waterfall-template').html())
.waterfall() ;

// 辅助方法，也可以使用underscore的template方法等等别的方式
var generateMarkupsFromData = function (data) {
  var markups = '';
  for (var i = 0; i < data.length; i++) {
    markups += ' \
      <ul class="pin list-group"> \
        <li class="list-group-item"> \
          <a href="javascript:;"> \
            <img src="images/' + data[i].imageFileName + '.jpg" /> \
          </a> \
        </li> \
      </ul> \
      ';
  }
  
  return markups;
};

$('.waterfall').on('finishing.mystist.waterfall', function () {
  // 在这里可以发起ajax请求, eg:
  $.ajax(url, function (newData) {
    // 拿到新的数据之后，把数据包装成markup的样子
    var markups = generateMarkupsFromData(newData);

    // 然后将markups添加进去：
    $('.waterfall').data('mystist.waterfall').addPins($(markups));
  });
});
```

**Comment by ZhuRuiHeng** [comment]
好的，谢谢，我试一下

**Comment by ZhuRuiHeng** [comment]
> @ZhuRuiHeng当页面滑动底部的时候，会触发一个“精”的回调，在那个回调里面可以请求AJAX获取数据，然后把数据添加进去。
> 
> 具体的代码：
> 
> ```js
> //初始化
> $（ ' .waterfall '）
> 。data（' bootstrap-waterfall-template '，$（'＃waterfall-template '）。html（））
> 。瀑布（）;
> 
> //辅助方法，也可以使用下划线的模板方法等等别的方式
> var  generateMarkupsFromData  =  function（ data）{
>    var markups =  ' ' ;
>   为（ VAR我 =  0 ;我 <  数据。长度 ;我 ++）{
>     标记+ =  ' \ 
>       <ul class =“pin list-group”> \ 
>         <li class =“list-group-item”> \ 
>           <a href="javascript:;"> \ 
>             <img src =“images / '  + data [i] .imageFileName  +  '. jpg“/> \ 
>           </a> \ 
>         </ li> \ 
>       </ ul> \ 
> ' ;      
>   }
>   
>   返回加价;
> };
> 
> $（'。 waterfall '）。on（' finishing.mystist.waterfall '，function（）{
>    //在这里可以发起ajax请求，例如：
>   $。ajax（url，function（newData）{
>      //拿到新的数据之后，把数据包装成标记的样子
>     VAR标记=  generateMarkupsFromData（newData）;
> 
>     //然后将
>     markups 添加进去：$（ '。 waterfall '）。数据（ ' mystist.waterfall '）。addPins（标记）;
>   }）;
> }）;
> ```

好的，谢谢，我试一下

**Comment by ViEqqedf** [comment]
你好，请问后端应该向前端返回怎样的数据？
是这样的，前端使用ajax发起请求，我们尝试过了让后端向前端返回List（我们当时只想看到新的Pins能生成），后台的数据在前端切实地接收到了。但是控制台一定会报错“TypeError: $elements.map is not a function”，然后页面没有添加新的Pins。错误来源为addPins函数中用到的decorate函数（bootstrap-waterfall的256行）。查询的一些资料表示我们应该发送map，但实验后结果不变，故有此问，非常感谢。
使用的浏览器为火狐的最新版本。

**Comment by ViEqqedf** [comment]
你好，请问后端应该向前端发送什么样的数据
是这样的，前端向后端发送ajax请求，我们尝试过让后端返回Map或List的数据，数据在前端切实地接收到了，但是页面并没有新的Pin生成，同时控制台报错“TypeError: $elements.map is not a function”，查找的一些资料表示我们应该发送map类型的数据，但在多次尝试以后依然无果，故有此问，非常感谢。

**Comment by ViEqqedf** [comment]
> ## 你好，请问生成的markups有什么要求吗
>请先看这里 修改：问题出在生成的markups在addPins中引发了下文提到的错误，我们使用的markups和你提供的样例一模一样。
> 是这样的，前端向后端发送ajax请求，我们尝试过让后端返回Map或List的数据，数据在前端切实地接收到了，但是页面并没有新的Pin生成，同时控制台报错“TypeError: $elements.map is not a function”，查找的一些资料表示我们应该发送map类型的数据，但在多次尝试以后依然无果，故有此问，非常感谢。

**Comment by liber-gong** [comment]
@ViEqqedf 不好意思，应该是我的问题，我上一条实例代码需要稍微修改一下：
`$('.waterfall').data('mystist.waterfall').addPins($(markups));`

之前markups是字符串，需要通过jQuery转换一下变成数组。

**Comment by ViEqqedf** [comment]
> @ViEqqedf 不好意思，应该是我的问题，我上一条实例代码需要稍微修改一下：
> `$('.waterfall').data('mystist.waterfall').addPins($(markups));`
> 
> 之前markups是字符串，需要通过jQuery转换一下变成数组。

喔我没注意到这个地方...我之前甚至在尝试自己在前台创建一个数组发给decorate，结果碰到了新的问题= =
非常感谢你的帮助！

**Comment by popsee** [comment]
You rock,man！谢谢作者，它解决了我的问题，我碰到同样的问题，瀑布流滚到最底部不能回调，这里发现可能是版本是旧的，我更新到最新的版本，Bug was gone。我试图修复它超过一天。但没考虑过是版本的问题！
Finally, i fixed it and so happy!
